---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: "plugins/docker:v19.03.8"
  settings:
    username:
      from_secret: docker_hub_user
    password:
      from_secret: docker_hub_access_token
    repo: robkaandorp/drone-portainer
    tags:
      - latest
      - ${DRONE_COMMIT_BRANCH}-${DRONE_BUILD_NUMBER}

trigger:
  branch:
  - master