---
version: 2
plan:
    project-key: DI
    key: DP
    name: di-drone-portainer

stages:
    - Build Stage:
        - Build

Build:
    requirements:
        - Docker
    tasks:
        - clean
        - script: |
            ${bamboo.capability.system.docker.executable} build \
                --pull --build-arg tag=portainer-v2.9-${bamboo.shortPlanName}-${bamboo.buildNumber} \
                -t robkaandorp/drone-portainer:portainer-v2.9-${bamboo.shortPlanName}-${bamboo.buildNumber} \
                -t robkaandorp/drone-portainer:latest .
        - script:
            - ${bamboo.capability.system.docker.executable} login --username robkaandorp --password ${bamboo.dockerhub_password}
            - ${bamboo.capability.system.docker.executable} push robkaandorp/drone-portainer:portainer-v2.9-${bamboo.shortPlanName}-${bamboo.buildNumber}
