name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: "${{ vars.VERSION_TAG }}.${{ github.run_number }}"
      IMAGE_NAME: "${{ secrets.REGISTRY_CATALOG }}/drone-portainer"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASS }}

    - name: Get Hash
      id: hash
      run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

    - name: Check Hash
      run: echo "${{ env.git_hash }}"

    - name: Build and push
      uses: docker/build-push-action@v3
      id: build
      with:
        push: true
        tags: |
          ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
          ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.git_hash }}

    - name: Result
      id: finish
      run: echo ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.git_hash }}
      
